### ISSUE TITLE
Support SonarQube 6.7 LTS

### ISSUE THREAD

**Issue by mwz** [mwz/sonar-scala-docker#2]
References:

- https://github.com/Sagacify/sonar-scala/issues/8
- https://github.com/Sagacify/sonar-scala/pull/23

**Comment by vinitty** [comment]
When will support for Scala be available for sonar 6.7?

**Comment by mwz** [comment]
Hi @vinitty, I'm waiting for https://github.com/Sagacify/sonar-scala/pull/23 to be merged and released, but it looks like the project has been abandoned, so I might release a new version of the plugin from my fork instead.

**Comment by vinitty** [comment]
Please let me know once done it will be really helpful for me

**Comment by vinitty** [comment]
Can you release a new version from your fork

**Comment by mwz** [comment]
Yeah, really close to releasing now, just testing compatibility with my existing projects to make sure that everything works fine. Any day now 😄

**Comment by mwz** [comment]
I've updated this project to use a new version of sonar-scala plugin, which I released from my branch [mwz/sonar-scala](https://github.com/mwz/sonar-scala).

**Comment by vinitty** [comment]
Thanks
