### ISSUE TITLE
difference between sonar-scala and sonar-scala-assembly

### ISSUE THREAD

**Issue by EslamElHusseiny** [mwz/sonar-scala-docker#6]
I just wanna understand the difference between `sonar-scala.jar` and `sonar-scala-assembly.jar`
And which one should I pull into my SonarQube installation?

**Comment by BalmungSan** [comment]
Hi @EslamElHusseiny, the difference is that the `assembly` one is the equivalent of a [maven **Uber** jar](https://stackoverflow.com/questions/11947037/what-is-an-uber-jar).
So, basically the first one only contains the sources of the plugin itself, while the other one contains those and all the dependencies of the plugin _(including the scala standard library)_.

**TL; DR**
Use `sonar-scala-assembly.jar`, it will include all the dependencies needed by the plugin.

**Comment by EslamElHusseiny** [comment]
Thanks a lot @BalmungSan 👍
